### ISSUE TITLE
页面报错，错误信息是：this.vccValidator is not a constructor

### ISSUE THREAD

**Issue by wonderfulo** [dev-zl/VccValidate#1]
如果有一个可以运行的demo就好了

**Comment by dev-zl** [comment]
`main.js`

**Comment by dev-zl** [comment]
`// main.js
import VccValidate from 'vcc-validate'
Vue.use(VccValidate)




<template>
  <div>
  <form>
    <input v-model="mdl['name']" v-vcc-field="'mdl[@name@]'" />
    <span>{{ vccTest.api().getMessagesOne('mdl[@name@]') }}</span>

    <input v-model="mdl['code']" v-vcc-field="'mdl[@code@]'" />
    <span>{{ vccTest.api().getMessagesOne('mdl[@code@]') }}</span>
  </form>
  </div>
</template>

export default {
  data() {
    return {
      vccTest: new this.VccValidate(),
      mdl: {
        id: '',
        name: '',
        code: ''
      },
    }
  },
  created() {
    this.vccTest.init(this, {
      openWarningLine: true,
      fields: {
        'mdl[@name@]': {
          validators: {
            notEmpty: {
              message: '请填写必填信息'
            }
          }
        },
        'mdl[@code@]': {
          validators: {
            notEmpty: {
              message: '请填写必填信息'
            }
          }
        }
      }
    })
  },
  methods: {
    handleOk() {
      this.vccTest.api().validate().then(res => {
        if (this.vccTest.api().isValid()) {

        }
      })
    }
  }
}` @

**Comment by dev-zl** [comment]
> 如果有一个可以运行的demo就好了

`// main.js
import VccValidate from 'vcc-validate'
Vue.use(VccValidate)




<template>
  <div>
  <form>
    <input v-model="mdl['name']" v-vcc-field="'mdl[@name@]'" />
    <span>{{ vccTest.api().getMessagesOne('mdl[@name@]') }}</span>

    <input v-model="mdl['code']" v-vcc-field="'mdl[@code@]'" />
    <span>{{ vccTest.api().getMessagesOne('mdl[@code@]') }}</span>
  </form>
  </div>
</template>

export default {
  data() {
    return {
      vccTest: new this.VccValidate(),
      mdl: {
        id: '',
        name: '',
        code: ''
      },
    }
  },
  created() {
    this.vccTest.init(this, {
      openWarningLine: true,
      fields: {
        'mdl[@name@]': {
          validators: {
            notEmpty: {
              message: '请填写必填信息'
            }
          }
        },
        'mdl[@code@]': {
          validators: {
            notEmpty: {
              message: '请填写必填信息'
            }
          }
        }
      }
    })
  },
  methods: {
    handleOk() {
      this.vccTest.api().validate().then(res => {
        if (this.vccTest.api().isValid()) {

        }
      })
    }
  }
}`

**Comment by dev-zl** [comment]
`// main.js`
`import VccValidate from 'vcc-validate'`
`Vue.use(VccValidate)`



`<template>`
`  <div>`
` <form>`
`    <input v-model="mdl['name']" v-vcc-field="'mdl[@name@]'" />`
`    <span>{{ vccTest.api().getMessagesOne('mdl[@name@]') }}</span>`

`    <input v-model="mdl['code']" v-vcc-field="'mdl[@code@]'" />`
`    <span>{{ vccTest.api().getMessagesOne('mdl[@code@]') }}</span>`
`  </form>`
`  </div>`
`</template>`

`export default { `
`  data() {`
`    return {`
`      vccTest: new this.VccValidate(),`
`      mdl: {`
`        id: '',`
`        name: '',`
`        code: ''`
`      },`
`    }`
`  },`
`  created() {`
`    this.vccTest.init(this, {`
`      openWarningLine: true,`
`      fields: {`
`        'mdl[@name@]': {`
`          validators: {`
`            notEmpty: {`
`              message: '请填写必填信息'`
`            }`
`          }`
`        },`
`        'mdl[@code@]': {`
`          validators: {`
`            notEmpty: {`
`              message: '请填写必填信息'`
`            }`
`          }`
`        }`
`      }`
`    })`
`  },`
`  methods: {`
`    handleOk() {`
`      this.vccTest.api().validate().then(res => {`
`        if (this.vccTest.api().isValid()) {`
`        }`
`      })`
`    }`
`      }`
`}`

**Comment by dev-zl** [comment]
> `// main.js`
> `import VccValidate from 'vcc-validate'`
> `Vue.use(VccValidate)`
> 
> `<template>`
> ` <div>`
> ` <form>`
> ` <input v-model="mdl['name']" v-vcc-field="'mdl[@name@]'" />`
> ` <span>{{ vccTest.api().getMessagesOne('mdl[@name@]') }}</span>`
> 
> ` <input v-model="mdl['code']" v-vcc-field="'mdl[@code@]'" />`
> ` <span>{{ vccTest.api().getMessagesOne('mdl[@code@]') }}</span>`
> ` </form>`
> ` </div>`
> `</template>`
> 
> `export default { `
> ` data() {`
> ` return {`
> ` vccTest: new this.VccValidate(),`
> ` mdl: {`
> ` id: '',`
> ` name: '',`
> ` code: ''`
> ` },`
> ` }`
> ` },`
> ` created() {`
> ` this.vccTest.init(this, {`
> ` openWarningLine: true,`
> ` fields: {`
> ` 'mdl[@name@]': {`
> ` validators: {`
> ` notEmpty: {`
> ` message: '请填写必填信息'`
> ` }`
> ` }`
> ` },`
> ` 'mdl[@code@]': {`
> ` validators: {`
> ` notEmpty: {`
> ` message: '请填写必填信息'`
> ` }`
> ` }`
> ` }`
> ` }`
> ` })`
> ` },`
> ` methods: {`
> ` handleOk() {`
> ` this.vccTest.api().validate().then(res => {`
> ` if (this.vccTest.api().isValid()) {`
> ` }`
> ` })`
> ` }`
> ` }`
> `}`

**Comment by dev-zl** [comment]
> `// main.js`
> `import VccValidate from 'vcc-validate'`
> `Vue.use(VccValidate)`
> 
> `<template>`
> ` <div>`
> ` <form>`
> ` <input v-model="mdl['name']" v-vcc-field="'mdl[@name@]'" />`
> ` <span>{{ vccTest.api().getMessagesOne('mdl[@name@]') }}</span>`
> 
> ` <input v-model="mdl['code']" v-vcc-field="'mdl[@code@]'" />`
> ` <span>{{ vccTest.api().getMessagesOne('mdl[@code@]') }}</span>`
> ` </form>`
> ` </div>`
> `</template>`
> 
> `export default { `
> ` data() {`
> ` return {`
> ` vccTest: new this.VccValidate(),`
> ` mdl: {`
> ` id: '',`
> ` name: '',`
> ` code: ''`
> ` },`
> ` }`
> ` },`
> ` created() {`
> ` this.vccTest.init(this, {`
> ` openWarningLine: true,`
> ` fields: {`
> ` 'mdl[@name@]': {`
> ` validators: {`
> ` notEmpty: {`
> ` message: '请填写必填信息'`
> ` }`
> ` }`
> ` },`
> ` 'mdl[@code@]': {`
> ` validators: {`
> ` notEmpty: {`
> ` message: '请填写必填信息'`
> ` }`
> ` }`
> ` }`
> ` }`
> ` })`
> ` },`
> ` methods: {`
> ` handleOk() {`
> ` this.vccTest.api().validate().then(res => {`
> ` if (this.vccTest.api().isValid()) {`
> ` }`
> ` })`
> ` }`
> ` }`
> `}`



> 如果有一个可以运行的demo就好了

**Comment by dev-zl** [comment]
> 如果有一个可以运行的demo就好了

https://dev-zl.github.io/VccValidate/#/quickstart?id=%e5%9f%ba%e6%9c%ac%e7%a4%ba%e4%be%8b
